// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from 'scenerystack/kite';
import bluetoothBString from './bluetoothBString.js';

export default new Shape( bluetoothBString ).makeImmutable();