// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from 'scenerystack/kite';
import creativeCommonsNdString from './creativeCommonsNdString.js';

export default new Shape( creativeCommonsNdString ).makeImmutable();