// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from 'scenerystack/kite';
import facebookFString from './facebookFString.js';

export default new Shape( facebookFString ).makeImmutable();