// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from 'scenerystack/kite';
import firstOrderString from './firstOrderString.js';

export default new Shape( firstOrderString ).makeImmutable();