// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from 'scenerystack/kite';
import firstOrderAltString from './firstOrderAltString.js';

export default new Shape( firstOrderAltString ).makeImmutable();