// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from 'scenerystack/kite';
import forumbeeString from './forumbeeString.js';

export default new Shape( forumbeeString ).makeImmutable();