// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from 'scenerystack/kite';
import ns8String from './ns8String.js';

export default new Shape( ns8String ).makeImmutable();