// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from 'scenerystack/kite';
import odnoklassnikiSquareString from './odnoklassnikiSquareString.js';

export default new Shape( odnoklassnikiSquareString ).makeImmutable();