// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from 'scenerystack/kite';
import piedPiperSquareString from './piedPiperSquareString.js';

export default new Shape( piedPiperSquareString ).makeImmutable();