// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from 'scenerystack/kite';
import rebelString from './rebelString.js';

export default new Shape( rebelString ).makeImmutable();