// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from 'scenerystack/kite';
import renrenString from './renrenString.js';

export default new Shape( renrenString ).makeImmutable();