// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from 'scenerystack/kite';
import twitchString from './twitchString.js';

export default new Shape( twitchString ).makeImmutable();