// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from 'scenerystack/kite';
import yarnString from './yarnString.js';

export default new Shape( yarnString ).makeImmutable();