// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from 'scenerystack/kite';
import babyCarriageSolidString from './babyCarriageSolidString.js';

export default new Shape( babyCarriageSolidString ).makeImmutable();