// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from 'scenerystack/kite';
import brailleSolidString from './brailleSolidString.js';

export default new Shape( brailleSolidString ).makeImmutable();