// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from 'scenerystack/kite';
import cubesSolidString from './cubesSolidString.js';

export default new Shape( cubesSolidString ).makeImmutable();