// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from 'scenerystack/kite';
import diceD20SolidString from './diceD20SolidString.js';

export default new Shape( diceD20SolidString ).makeImmutable();