// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from 'scenerystack/kite';
import diceSolidString from './diceSolidString.js';

export default new Shape( diceSolidString ).makeImmutable();