// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from 'scenerystack/kite';
import fastForwardSolidString from './fastForwardSolidString.js';

export default new Shape( fastForwardSolidString ).makeImmutable();