// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from 'scenerystack/kite';
import fileImageSolidString from './fileImageSolidString.js';

export default new Shape( fileImageSolidString ).makeImmutable();