// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from 'scenerystack/kite';
import handshakeRegularString from './handshakeRegularString.js';

export default new Shape( handshakeRegularString ).makeImmutable();