// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from 'scenerystack/kite';
import highlighterSolidString from './highlighterSolidString.js';

export default new Shape( highlighterSolidString ).makeImmutable();