// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from 'scenerystack/kite';
import laptopCodeSolidString from './laptopCodeSolidString.js';

export default new Shape( laptopCodeSolidString ).makeImmutable();