// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from 'scenerystack/kite';
import leafSolidString from './leafSolidString.js';

export default new Shape( leafSolidString ).makeImmutable();