// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from 'scenerystack/kite';
import lemonSolidString from './lemonSolidString.js';

export default new Shape( lemonSolidString ).makeImmutable();