// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from 'scenerystack/kite';
import objectGroupSolidString from './objectGroupSolidString.js';

export default new Shape( objectGroupSolidString ).makeImmutable();