// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from 'scenerystack/kite';
import rulerSolidString from './rulerSolidString.js';

export default new Shape( rulerSolidString ).makeImmutable();