// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from 'scenerystack/kite';
import slashSolidString from './slashSolidString.js';

export default new Shape( slashSolidString ).makeImmutable();