// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from 'scenerystack/kite';
import smileSolidString from './smileSolidString.js';

export default new Shape( smileSolidString ).makeImmutable();