// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from 'scenerystack/kite';
import starOfLifeSolidString from './starOfLifeSolidString.js';

export default new Shape( starOfLifeSolidString ).makeImmutable();