// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from 'scenerystack/kite';
import taxiSolidString from './taxiSolidString.js';

export default new Shape( taxiSolidString ).makeImmutable();