// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from 'scenerystack/kite';
import theaterMasksSolidString from './theaterMasksSolidString.js';

export default new Shape( theaterMasksSolidString ).makeImmutable();