// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from 'scenerystack/kite';
import tractorSolidString from './tractorSolidString.js';

export default new Shape( tractorSolidString ).makeImmutable();