// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from 'scenerystack/kite';
import universitySolidString from './universitySolidString.js';

export default new Shape( universitySolidString ).makeImmutable();