// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from 'scenerystack/kite';
import userTieSolidString from './userTieSolidString.js';

export default new Shape( userTieSolidString ).makeImmutable();