// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from 'scenerystack/kite';
import usersCogSolidString from './usersCogSolidString.js';

export default new Shape( usersCogSolidString ).makeImmutable();