// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from 'scenerystack/kite';
import userShieldSolidString from './userShieldSolidString.js';

export default new Shape( userShieldSolidString ).makeImmutable();