// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from 'scenerystack/kite';
import utensilSpoonSolidString from './utensilSpoonSolidString.js';

export default new Shape( utensilSpoonSolidString ).makeImmutable();