// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from 'scenerystack/kite';
import wifiSolidString from './wifiSolidString.js';

export default new Shape( wifiSolidString ).makeImmutable();